comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

coverage:
  range: "30..75"
  round: down
  precision: 2
  status:
    project:
      default:
        # basic
        target: 40%
        threshold: 0%
        # advanced settings
        if_ci_failed: error
        informational: false
        only_pulls: false