name: Codecov

on:
  push:
    branches: [ main, qa, development ]

  workflow_dispatch:

jobs:
  testing_codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install
      
      - name: CODECOV - Upload coverage results
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true


