name: Deploy Develop

on:
  workflow_run:
    workflows: ["Codecov"]
    branches: [main]
    types:
      - completed
    paths-ignore:
      - '**.md'

jobs:
  deploy_dev:
    name: Deploy to develop
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Checkout code
      run: echo 'failure'